<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>
      $(NetFrameworkTargetFrameworks);
      $(NetCoreTargetFrameworks);
      $(NetStandardTargetFrameworks)
    </TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>ASP.NET Core Data Protection integration package for the OpenIddict client services.</Description>
    <PackageTags>$(PackageTags);client;dataprotection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenIddict.Client\OpenIddict.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!--
      Note: the versions of the System.Security.Cryptography.Xml package that are transitively referenced are
      known to be affected by different vulnerabilities (see https://github.com/advisories/GHSA-w3x6-4m5h-cxqf
      and https://github.com/advisories/GHSA-37gx-xxp4-5rgx for more information). To mitigate this issue,
      the package is explicitly referenced here to ensure that a fixed version is used.
    -->

    <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="OpenIddict.Abstractions" />
    <Using Include="OpenIddict.Abstractions.OpenIddictConstants" Static="true" />
    <Using Include="OpenIddict.Abstractions.OpenIddictResources" Alias="SR" />
    <Using Include="OpenIddict.Client.OpenIddictClientEvents" Static="true" />
    <Using Include="OpenIddict.Client.OpenIddictClientHandlers" Static="true" />
    <Using Include="OpenIddict.Client.OpenIddictClientHandlerFilters" Static="true" />
    <Using Include="OpenIddict.Client.DataProtection.OpenIddictClientDataProtectionHandlers" Static="true" />
    <Using Include="OpenIddict.Client.DataProtection.OpenIddictClientDataProtectionHandlerFilters" Static="true" />
  </ItemGroup>

</Project>
