<Project>

  <Import Project="Sdk.targets" Sdk="Microsoft.DotNet.Arcade.Sdk" />

  <!--
    Note: Arcade automatically replaces copyrights defined in .props or .csproj files
    by the default Microsoft copyright. To ensure this doesn't happen, the replaced
    copyright is restored in this .targets file using the private variable set in .props.
    Similarly, both delayed and public signing are disabled to override Arcade's defaults.
  -->
  
  <PropertyGroup>
    <Copyright>$(_ProjectCopyright)</Copyright>
    <DelaySign>false</DelaySign>
    <PublicSign>false</PublicSign>
  </PropertyGroup>

  <!--
    Note: the trimming and Native AOT analyzers are only supported on .NET.
  -->

  <PropertyGroup Condition=" $(RepoRelativeProjectDir.Contains('src')) And '$(TargetFrameworkIdentifier)' == '.NETCoreApp' ">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <!--
    Note: .NET Framework assemblies are not annotated with nullable references
    annotations. To avoid errors on these target frameworks, related warnings
    are disabled by setting <Nullable> to "annotations" instead of "enable".
  -->

  <PropertyGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' ">
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETCoreApp' ">
    <SupportedOSPlatformVersion Condition=" '$(TargetPlatformIdentifier)' == 'Android'     ">21.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition=" '$(TargetPlatformIdentifier)' == 'iOS'         ">12.2</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition=" '$(TargetPlatformIdentifier)' == 'MacCatalyst' ">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition=" '$(TargetPlatformIdentifier)' == 'macOS'       ">12.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition=" '$(TargetPlatformIdentifier)' == 'Windows'     ">7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <!--
    Note: metapackages don't include any build output. To ensure the TFM-specific folders under
    /lib are preserved, a placeholder file is added for each supported target framework moniker.
  -->

  <Target Name="AddTfmSpecificPlaceholders" Condition=" '$(IncludeBuildOutput)' != 'true' ">
    <GetNuGetShortFolderName TargetFrameworkMoniker="$(TargetFrameworkMoniker)"
                             TargetPlatformMoniker="$(TargetPlatformMoniker)">
      <Output TaskParameter="NuGetShortFolderName" PropertyName="_NuGetShortFolderName" />
    </GetNuGetShortFolderName>

    <ItemGroup>
      <TfmSpecificPackageFile Include="$(MSBuildThisFileDirectory)eng\_._"
                              PackagePath="lib\$(_NuGetShortFolderName)\_._" />
    </ItemGroup>
  </Target>

  <!--
    Note: Arcade always generates .resx backing files with internal static methods/constants.
    To ensure the OpenIddict resources are public, the default visibility is manually overridden.
  -->

  <Target Name="OverrideResourcesVisibility" Condition=" @(EmbeddedResourceSGResx) != '' " AfterTargets="_GenerateResxSource">
    <WriteLinesToFile
        File=" %(EmbeddedResourceSGResx.SourceOutputPath) "
        Lines=" $([System.IO.File]::ReadAllText(%(EmbeddedResourceSGResx.SourceOutputPath))
            .Replace('internal const', 'public const')
            .Replace('internal static', 'public static')
            .Replace('static partial class', 'partial class')) "
        Overwrite="true"
        Encoding="Unicode" />
  </Target>

</Project>
