<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>
      $(NetFrameworkTargetFrameworks);
      $(NetCoreTargetFrameworks);
      $(NetStandardTargetFrameworks)
    </TargetFrameworks>
    <IncludeInternalExtensions>false</IncludeInternalExtensions>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Relational entities for the OpenIddict Entity Framework 6.x stores.</Description>
    <PackageTags>$(PackageTags);entityframework;models</PackageTags>
  </PropertyGroup>

</Project>
