<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>
      net472;
      net48;
      $(NetCoreTargetFrameworks);
      netstandard2.1
    </TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>MongoDB stores for OpenIddict.</Description>
    <PackageTags>$(PackageTags);mongodb</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenIddict.Core\OpenIddict.Core.csproj" />
    <ProjectReference Include="..\OpenIddict.MongoDb.Models\OpenIddict.MongoDb.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!--
      Note: the versions of the SharpCompress and Snappier packages that are transitively referenced are
      known to be affected by security vulnerabilities (see https://github.com/advisories/GHSA-6c8g-7p36-r338
      and https://github.com/advisories/GHSA-pggp-6c3x-2xmx for more information). To mitigate this issue,
      the packages are explicitly referenced here to ensure that fixed versions are used.
    -->

    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="SharpCompress" />
    <PackageReference Include="Snappier" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="MongoDB.Bson" />
    <Using Include="MongoDB.Driver" />
    <Using Include="MongoDB.Driver.Linq" />
    <Using Include="OpenIddict.Abstractions" />
    <Using Include="OpenIddict.Abstractions.OpenIddictConstants" Static="true" />
    <Using Include="OpenIddict.Abstractions.OpenIddictResources" Alias="SR" />
  </ItemGroup>

</Project>
