/*
 * Licensed under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 * See https://github.com/openiddict/openiddict-core for more information concerning
 * the license and the contributors participating to this project.
 */

using Properties = OpenIddict.Client.WebIntegration.OpenIddictClientWebIntegrationConstants.Properties;

namespace OpenIddict.Client.WebIntegration;

/// <summary>
/// Exposes companion extensions for the OpenIddict client Web integration.
/// </summary>
public static partial class OpenIddictClientWebIntegrationHelpers
{
    public static string? GetProviderName(this OpenIddictClientRegistration registration)
    {
        if (registration is null)
        {
            throw new ArgumentNullException(nameof(registration));
        }

        return registration.Properties.TryGetValue(Properties.ProviderName, out var provider)
            && provider is string value ? value : null;
    }

    public static TSettings? GetProviderSettings<TSettings>(this OpenIddictClientRegistration registration)
        where TSettings : OpenIddictClientWebIntegrationSettings
    {
        if (registration is null)
        {
            throw new ArgumentNullException(nameof(registration));
        }

        return registration.Properties.TryGetValue(Properties.ProviderSettings, out var value)
            && value is TSettings settings ? settings : null;
    }

    // Note: provider-specific helpers are automatically generated by a source generator.
}
