/*
 * Licensed under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 * See https://github.com/openiddict/openiddict-core for more information concerning
 * the license and the contributors participating to this project.
 */

namespace OpenIddict.Client.WebIntegration;

/// <summary>
/// Exposes common constants used by the OpenIddict client Web integration services.
/// </summary>
public static partial class OpenIddictClientWebIntegrationConstants
{
    // Note: provider name constants are automatically generated by the source generator.

    public static class Properties
    {
        public const string ProviderName = ".provider_name";
        public const string ProviderSettings = ".provider_settings";
    }
}
