/*
 * Licensed under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 * See https://github.com/openiddict/openiddict-core for more information concerning
 * the license and the contributors participating to this project.
 */

namespace OpenIddict.Client.WebIntegration;

/// <summary>
/// Exposes the provider-specific environments supported by the OpenIddict client Web integration services.
/// </summary>
public static partial class OpenIddictClientWebIntegrationEnvironments
{
    // Note: environments are automatically generated by the source generator.
}
