/*
 * Licensed under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 * See https://github.com/openiddict/openiddict-core for more information concerning
 * the license and the contributors participating to this project.
 */

namespace OpenIddict.Client.WebIntegration;

/// <summary>
/// Exposes the provider-specific scopes supported by the OpenIddict client Web integration services.
/// </summary>
public static partial class OpenIddictClientWebIntegrationScopes
{
    // Note: scopes are automatically generated by the source generator.
}
