<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetCoreTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenIddict.Client.Saml.AspNetCore\OpenIddict.Client.Saml.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\OpenIddict.Server.Saml\OpenIddict.Server.Saml.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\OpenIddict.Client.Saml.Tests\OpenIddictClientSamlTestHelpers.cs" Link="OpenIddictClientSamlTestHelpers.cs" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="OpenIddict.Abstractions" />
    <Using Include="OpenIddict.Abstractions.OpenIddictConstants" Static="true" />
    <Using Include="OpenIddict.Abstractions.OpenIddictResources" Alias="SR" />
  </ItemGroup>

</Project>
