<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetFrameworkTargetFrameworks);$(NetCoreTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenIddict.Client.Saml\OpenIddict.Client.Saml.csproj" />
    <ProjectReference Include="..\..\src\OpenIddict.Server.Saml\OpenIddict.Server.Saml.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="OpenIddict.Abstractions" />
    <Using Include="OpenIddict.Abstractions.OpenIddictConstants" Static="true" />
    <Using Include="OpenIddict.Abstractions.OpenIddictResources" Alias="SR" />
  </ItemGroup>

</Project>
