name: push

on:
  push:
    branches:
      - dev

jobs:
  sponsor_job:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Generate sponsors section
      uses: JamesIves/github-sponsors-readme-action@2fd9142e765f755780202122261dc85e78459405 # v1.6.0
      with:
        token: ${{ secrets.SPONSORS_TOKEN }}
        file: 'README.md'

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
      with:
        branch: dev
        folder: '.'
        token: ${{ secrets.GITHUB_TOKEN }}
        git-config-name: OpenIddict Bot
        git-config-email: 32257313+openiddict-bot@users.noreply.github.com
        commit-message: Update the sponsors section
